window.englishComments = [
“HAN and Tods are a perfect match”, 
“HAN fits Tods image so well”,
“HAN brings a nice energy to Tods”,
“Tods and HAN look amazing together!”,
“HAN was made for Tods”,
“HAN looks great in Tods style”,
“This HAN and Tods pairing feels so natural”,
“HAN really complements Tods aesthetic”,
“HAN adds something special to Tods”
“HAN and Tods just make sense”,
“HAN represents Tods beautifully”,
“Tods looks amazing with HAN”,
“HAN's image works perfectly with Tods”,
“HAN and Tods are such a strong combination”,
“This collaboration is awesome!”,
“HAN brings a modern touch to Tods”,
“Tods and HAN are a great fashion duo”,
“HAN fits perfectly with Tods elegant vibe”,
“HAN makes Tods look even more exciting”,
“HAN's style matches Tods perfectly”,
“HAN and Tods share the same elegance”,
“HAN gives Tods a cool perspective”,
“HAN and Tods belong together”,
“Tods couldn't have chosen better”,
“HAN was the perfect choice for Tods”,
“HAN shines with Tods”,
“HAN brings Tods to a new audience!”
“Tods and HAN work so well together!”
“HAN's personality fits Tods nicely”,
“HAN elevates every Tods look”,
“HAN's fashion sense is always impressive”,
“HAN wears every look effortlessly”,
“HAN's style keeps getting better!”,
“HAN always stands out in fashion”,
“HAN has such a natural fashion presence”,
“HAN makes every outfit look awesome!”,
“HAN's style is nice and neat”,
“HAN always brings something nice”,
“HAN knows how to own a look”,
“HAN looks incredible in every outfit”,
“HAN's style feels so effortless”,
“HAN's fashion journey is exciting to watch!”,
“HAN always looks confident and stylish”,
“HAN makes fashion look fun”,
“HAN has a unique sense of style”,
“HAN has an amazing sense of style”,
“HAN has an incredible sense of fashion”,
“HAN's style feels authentic”,
“HAN always looks comfortable and confident”,
“HAN's fashion choices are always good!”,
“HAN has great fashion instincts”,
“HAN's style speaks for itself”,
“HAN's vibe speaks for itself”,
“HAN always leaves a good impression”,
“HAN knows how to make a fashion statement”,
“HAN's looks never disappoint”,
“HAN's visuals never disappoint”,
“HAN always delivers great fashion looks”,
“HAN belongs at Milan Fashion Week”,
“HAN looks right at home in Milan”,
“HAN is shining in Milan”,
“HAN and Milan Fashion Week are a perfect fit”,
“HAN brings excitement to Milan Fashion Week”,
“Seeing HAN in Milan is amazing!”,
“HAN looks incredible at Milan Fashion Week”,
“Milan Fashion Week suits HAN perfectly”,
“HAN's presence makes Milan Fashion Week even more exciting!”,
“HAN is having such a great time in Milan”,
“HAN looks so stylish in Milan”,
“HAN is making Milan Fashion Week memorable”,
“HAN is one of the highlights of Milan Fashion Week”,
“HAN fits right into Milan's fashion scene”,
“HAN is stunning in Milan”,
“HAN brings fresh energy to Milan Fashion Week”,
“HAN is made for events like Milan Fashion Week”,
“HAN looks amazing in Milan”,
“HAN is turning heads in Milan”,
“Todss craftsmanship is always impressive”,
“Tods attention to detail is incredible”,
“Tods continues to define timeless style”,
“Tods quality always stands out”,
“Tods designs are effortlessly elegant!”,
“Tods never goes out of style”,
“Tods represents Italian excellence”,
“Tods always delivers sophisticated style!”,
“Tods remains one of the most elegant brands”,
“Tods combines quality and style perfectly”,
“Tods elegance is unmistakable”,
“HAN fits perfectly into the luxury fashion world”,
“HAN brings a fresh vibe to luxury fashion”,
“HAN has a strong fashion presence”,
“HAN continues to grow as a fashion icon”,
“HAN is making his mark in fashion”,
“HAN's influence in fashion keeps growing”,
“HAN has a natural connection to fashion”,
“HAN is becoming a standout name in fashion”,
“HAN continues to impress in the fashion world”
];
