window.englishComments = [
"HAN and Tod's are a perfect match",
"HAN fits Tod's brand image so well",
"HAN brings fresh energy to Tod's",
"Tod's and HAN look amazing together!",
"HAN was made for Tod's",
"HAN looks great in Tod's style",
"This HAN and Tod's pairing feels so natural",
"HAN really complements Tod's aesthetic",
"HAN adds something special to Tod's",
"HAN and Tod's just make sense",
"HAN represents Tod's beautifully",
"Tod's looks amazing with HAN",
"HAN's presence works beautifully with Tod's",
"HAN and Tod's are such a strong combination",
"HAN brings a modern touch to Tod's",
"Tod's and HAN are a great fashion pairing",
"HAN fits perfectly with Tod's elegant vibe",
"HAN makes Tod's look even more exciting",
"HAN's style matches Tod's perfectly",
"HAN and Tod's share the same elegance",
"HAN gives Tod's a fresh perspective",
"HAN and Tod's belong together",
"Tod's couldn't have chosen better",
"HAN was the perfect choice for Tod's",
"HAN shines with Tod's",
"HAN brings Tod's to a new audience!",
"Tod's and HAN work so well together!",
"HAN's personality fits Tod's nicely",
"HAN elevates every Tod's look",
"HAN's fashion sense is always impressive",
"HAN wears every look effortlessly",
"HAN's style keeps getting better!",
"HAN always stands out in fashion",
"HAN has such a natural fashion presence",
"HAN makes every outfit look awesome!",
"HAN's style is clean, and elegant",
"HAN always brings something special",
"HAN knows how to own a look",
"HAN looks incredible in every outfit",
"HAN's style feels so effortless",
"HAN's fashion journey is exciting to watch!",
"HAN always looks confident and stylish",
"HAN makes fashion look fun",
"HAN has a unique sense of style",
"HAN has an amazing sense of style",
"HAN has an incredible sense of fashion",
"HAN's style feels authentic",
"HAN always looks comfortable and confident",
"HAN's fashion choices are always good!",
"HAN has great fashion instincts",
"HAN's style speaks for itself",
"HAN's vibe speaks for itself",
"HAN always leaves a good impression",
"HAN knows how to make a fashion statement",
"HAN's looks never disappoint",
"HAN's visuals never disappoint",
"HAN always delivers great fashion looks",
"HAN belongs at Milan Fashion Week",
"HAN looks right at home in Milan",
"HAN is shining in Milan",
"HAN and Milan Fashion Week are a perfect fit",
"HAN brings excitement to Milan Fashion Week",
"Seeing HAN in Milan is amazing!",
"HAN looks incredible at Milan Fashion Week",
"Milan Fashion Week suits HAN perfectly",
"HAN's presence makes Milan Fashion Week even more exciting!",
"HAN looks so happy to be in Milan",
"HAN looks so stylish in Milan",
"HAN is making this Milan Fashion Week even more memorable",
"HAN is one of the highlights of Milan Fashion Week",
"HAN fits right into Milan's fashion scene",
"HAN is stunning in Milan",
"HAN brings fresh energy to Milan Fashion Week",
"HAN is made for events like Milan Fashion Week",
"HAN looks amazing in Milan",
"HAN is turning heads in Milan",
"Tod's craftsmanship is always impressive",
"Tod's attention to detail is incredible",
"Tod's continues to define timeless style",
"Tod's quality always stands out",
"Tod's designs are effortlessly elegant!",
"Tod's never goes out of style",
"Tod's represents Italian excellence",
"Tod's always delivers sophisticated style!",
"Tod's remains one of the most elegant brands",
"Tod's combines quality and style perfectly",
"Tod's elegance is unmistakable",
"HAN fits perfectly into the luxury fashion world",
"HAN brings a fresh vibe to luxury fashion",
"HAN has a strong fashion presence",
"HAN continues to grow as a fashion icon",
"HAN is making his mark in fashion",
"HAN's influence in fashion keeps growing",
"HAN feels so natural in the fashion world",
"HAN is becoming a standout presence in fashion",
"HAN continues to impress in the fashion world",
"This is such a big fashion moment for HAN",
"Milan looks even better with HAN there",
"The way HAN carries himself is so effortlessly stylish",
"There is something so natural about seeing HAN in this setting",
"HAN has that confidence that works so well for fashion",
"Seeing HAN at Milan Fashion Week still feels unreal",
"The Tod's styling on HAN is so clean and elegant",
"This look suits HAN so much",
"The fashion world needs more HAN moments like this",
"Milan Fashion Week with HAN is already iconic to me",
"There is such an easy elegance to HAN's style",
"Tod's and HAN together feel expensive in the best way",
"HAN brings personality to every fashion moment",
"HAN looks so at ease in the fashion scene",
"This is one of those HAN moments people will remember",
"There is something very timeless about HAN in Tod's",
"The camera really loves HAN in Milan",
"Everything about HAN’s appearance feels so tasteful",
"The whole Tod’s mood feels even more expensive with HAN there",
"HAN’s charm works so well in a high-fashion setting",
"I really love seeing this more mature side of HAN",
"HAN looks like he stepped right into an Italian fashion editorial"
];
