window.spanishComments = [
"HAN y Tods son la combinación perfecta", 
"HAN encaja muy bien con Tods",
"HAN brinda una buena energía para Tods",
"Tods y HAN son una gran combinación!",
"HAN fue hecho para Tods",
"HAN se ve increíble en el estilo de Tods",
"La combinación de HAN y Tods se siente tan natural",
"HAN realmente complementa la estética de Tods",
"HAN le da ese toque especial a Tods",
"HAN y Tods suenan bien juntos",
"HAN representa a Tods de una forma bellísima",
"Tods luce increíble con HAN",
"La imagen de HAN encaja perfectamente con Tods",
"HAN y Tods son una combinación poderosa",
"Esta colaboración es increíble!",
"HAN le da un toque moderno a Tods",
"Tods y HAN son un gran dúo de moda",
"HAN encaja perfectamente con la vibra elegante de Tods",
"HAN hace que Tods sea mucho más emocionante",
"El estilo de HAN encaja con Tods perfectamente",
"HAN y Tods tienen la misma elegancia",
"HAN le da una perspectiva genial a Tods",
"HAN y Tods están hechos el uno para el otro",
"Tods no podría haber elegido un mejor invitado",
"HAN fue la mejor elección de Tods",
"HAN brilla con Tods",
"HAN le da a Tods un nuevo público!",
"Tods y HAN funcionan de maravilla juntos!",
"La personalidad de HAN encaja bien con Tods",
"HAN hace lucir bien cualquier outfit de Tods",
"El sentido de la moda de HAN siempre es impactante",
"HAN se ve increíble con cualquier cosa",
"El estilo de HAN siempre es bueno!",
"HAN siempre destaca en la moda",
"HAN tiene una presencia naturalmente a la moda",
"HAN hace que cada outfit se vea increíble!",
"El estilo de HAN siempre es atractivo y genial",
"HAN siempre se luce",
"HAN sabe como lucir un outfit",
"HAN se ve hermoso con cualquier outfit",
"HAN siempre se ve increíble naturalmente",
"Ver a HAN crecer en el mundo de la moda es emocionante!",
"HAN siempre se ve encantador y a la moda",
"HAN hace que la moda sea entretenida",
"HAN tiene un sentido de la moda único",
"HAN tiene un sentido de la moda increíble",
"HAN tiene un sentido de la moda impresionante",
"El estilo de HAN es auténtico",
"HAN está deslumbrante!",
"HAN irradia belleza y estilo",
"La energía de HAN es increíble",
"HAN siempre deja una buena impresión",
"HAN sabe cómo lucirse cuando se trata de moda",
"El visual de HAN nunca decepciona",
"HAN siempre luce encantador",
"HAN siempre está a la moda",
"HAN en Milán Fashion Week",
"HAN se ve como en casa en Milán",
"HAN en Milán es fenomenal!",
"HAN y MFW son la combinación perfecta",
"Me emociona ver a HAN en la Fashion Week",
"Ver a HAN en Milán es increíble!",
"HAN se ve increíble en la Fashion Week de Milán",
"Necesitaba ver a HAN en MFW",
"HAN hace que MFW sea más emocionante",
"HAN la está pasando genial en Milán",
"HAN luce a la moda en Milán",
"HAN hace que MFW sea memorable",
"HAN destaca en la Fashion Week de Milán",
"HAN encaja perfecto con la moda de Milán",
"Ver a HAN en Milán es estupendo!",
"HAN brinda una energía positiva a la Fashion Week",
"Ya se necesitaba a HAN en eventos como la Fashion Week",
"Ver a HAN en Milán es magnífico",
"Ver a HAN en Milán es maravilloso",
"Tods tiene prendas de lujo",
"La atención al detalle de Tods es increíble",
"El estilo de Tods nunca pasa de moda",
"La calidad de Tods siempre resalta",
"Los diseños de Tods son muy elegantes!",
"Tods nunca pasa de moda",
"Tods representa la excelencia italiana",
"Tods siempre muestra estilos sofisticados!",
"Tods sigue siendo una de las marcas más elegantes",
"Tods combina calidad y estilo perfectamente",
"La elegancia de Tods inconfundible",
"HAN encaja perfectamente en la moda de lujo",
"HAN le da una energía refrescante a la moda de lujo",
"HAN tiene una presencia muy a la moda",
"HAN continúa creciendo como icono de la moda",
"HAN está dejando su marca en la moda",
"La influencia de HAN en la moda sigue creciendo",
"HAN encaja perfectamente en el mundo de la moda",
"HAN se abre camino en el mundo de la moda",
"HAN continúa dejando su marca en el mundo de la moda"
];
